### ISSUE TITLE
why is hidden layer initialized only on beginning of an epoch?

### ISSUE THREAD

**Issue by realiti4** [salesforce/awd-lstm-lm#112]
If someone can help me with this I'd be thankful, I couldn't understand this part. Why are we keeping the hidden layer for whole train dataset until epoch finishes? Isn't that bad for testing and predicting later on? Thanks..

**Comment by mjudell** [comment]
It's the initial hidden states being initialized.  Figure 1 in [An Analysis of Neural Language Modeling at Multiple Scales](https://arxiv.org/abs/1803.08240) shows why you might want to do that.  The model becomes more confident as it gets more context.  If you initialized to zero, that climb might be a little shallower.  There's also a [blog](https://r2rt.com/non-zero-initial-states-for-recurrent-neural-networks.html) post that discusses the situation.

**Comment by realiti4** [comment]
Thanks I'm checking them right now.
