### ISSUE TITLE
Hidden state init of LSTM layers (after the first)

### ISSUE THREAD

**Issue by mourga** [salesforce/awd-lstm-lm#116]
This code 'breaks' a multi-layer LSTM to `l` different 1-layer LSTMs. So after the forward pass of the first LSTM, the hidden state of the next LSTM should be initialised with the previous hidden state. To this end, shouldn't the following line of the code be inside the for loop??  
https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/model.py#L88

In my understanding, every LSTM is trained with an initial hidden state of zeros, which is ok for the first layer, but isn't it wrong that hidden states do not 'propagate' to the next layers?

Thanks in advance.

**Comment by ccarter-cs** [comment]
No, that code is fine. The initial hidden state is set https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/main.py#L177 .  This variable is re-assigned here https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/main.py#L196 . Finally the gradients from the previous mb are detached here https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/main.py#L193 . 

Note: I have nothing to do with this project, but hope I have helped.

**Comment by mourga** [comment]
Thank you for your reply. My problem is exactly with this line:
https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/model.py#L81
because as I debug it `hidden[0]` (layer 0) is zeros as expected, but after the first iteration, `hidden[1]` (layer 1) is zeros again (because the list `hidden` does not change). 

I though that the hidden states of each layer should be initialised with the hidden states of the previous layer, just like with the input. You can see in the line above that the output of every layer becomes input to the next one (`raw_output` is the same name for input and output). This does not happen with the hidden state (`hidden[l]` != `new_h`).

The most possible scenario is that I miss something, I hope I'm not confusing anyone! Thanks again

**Comment by ccarter-cs** [comment]
Each layer of an RNN has it's own hidden. These will all start at 0 and be updated to different values. The return from the forward function here returns the hiddens for each layer in a list. On the next mb, these will be used as the starting point.  To see this, run 1 MB through and look at new_hidden. It will be of length  = num_layers and contain different values.  You can also see this in the init_hidden function that creates the properly shaped initial hidden, 1 for each layer of the RNN.
