### ISSUE TITLE
Multiple GPU option

### ISSUE THREAD

**Issue by songyuzhou324** [salesforce/awd-lstm-lm#38]
I extended the code to multiple GPU training, but the GPU usage is extremely imbalanced. The root cause is that we collect all outputs back and calculate loss on one GPU. I tried to put loss calculation inside model.forward() as following:

class RNNModel(nn.Module):
&nbsp; &nbsp; &nbsp; &nbsp; def __init__(...):
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; super(RNNModel, self).__init__()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; from splitcross import SplitCrossEntropyLoss
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; splits = [2800, 20000, 76000]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; self.criterion = SplitCrossEntropyLoss(ninp, splits=splits, verbose=False)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ... ...
&nbsp; &nbsp; &nbsp; &nbsp; def forward(...)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ... ...
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; result = output
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; # calculate loss
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; result = result.view(result.size(0)*result.size(1), -1)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; raw_loss = self.criterion(decoder_weight, decoder_bias, result, target)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; loss = raw_loss
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; # activation regularization
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if args.alpha: loss = loss + sum(args.alpha * dropped_rnn_h.pow(2).mean() for dropped_rnn_h in outputs[-1:])
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; # Temporal Activation Regularization (slowness)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if args.beta: loss = loss + sum(args.beta * (rnn_h[1:] - rnn_h[:-1]).pow(2).mean() for rnn_h in raw_outputs[-1:])
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; # expand loss to two dimensional space so it can be gathered via the second dimension
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; loss = loss.unsqueeze(1)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; raw_loss = raw_loss.unsqueeze(1)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if return_h:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return raw_loss, loss, hidden, raw_outputs, outputs
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return raw_loss, loss, hidden

Then, in my main.py, I collect the loss and use loss.mean().backward() to update parameters. The interesting thing is, I can successfully finish the first round loss.mean().backward() but failed the second round with error:

RuntimeError: invalid argument 3: Index tensor must have same dimensions as input tensor at
 /pytorch/torch/lib/THC/generic/THCTensorScatterGather.cu:199

Can anyone help?
Thanks in advance!

**Comment by songyuzhou324** [comment]
I think I need to wrap a module into DataParallel in order to split target in dim=1 as well. I'm not able to make it so far. Can anyone help?

Thanks in advance!

**Comment by songyuzhou324** [comment]
Finally I resolved this issue. I need to reshape output after being collected, instead of reshape output in the forward function. Otherwise, the target is not the correct one for every timestamp.

**Comment by songyuzhou324** [comment]
The error message is still hard to track. However, I found a workaround. Mount the Criterion on multiple GPUs separately, replicate model.decoder.weights and model.decoder.bias, and feed to Criterion will work. The GPU memory usage is still a little unpredictable but much more balanced now.

**Comment by PermiJW** [comment]
Hey Songyu, I got the same imbalanced situation as you. Can you tell me how you achieved the workaround? Thanks

**Comment by songyuzhou324** [comment]
> Hey Songyu, I got the same imbalanced situation as you. Can you tell me how you achieved the workaround? Thanks

put your loss calculation inside forward() will mitigate the issue but can't completely resolve it. Probably migrate to Tensorflow:P

**Comment by PermiJW** [comment]
Thanks I will try it :)
