### ISSUE TITLE
Error in moving to GPU

### ISSUE THREAD

**Issue by Taha-Bahadori** [salesforce/awd-lstm-lm#4]
@Smerity  I tried the following code:
```python
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.gru = nn.GRU(10, 10)
        self.gru = WeightDrop(self.gru, ['weight_hh_l0'], dropout=0.5)

m = Model()
# The following operation throws an error
m.cuda()
```
Can you take a look and see where the problem occurs? I am using PyTorch 0.2.

**Comment by Smerity** [comment]
As noted in the [README](https://github.com/salesforce/awd-lstm-lm/tree/4582a1e9ecb1de177c01d01510dccd00b9abbbde#software-requirements), `PyTorch 0.1.12` is currently required, with one reason being that `WeightDrop` needs to be updated.

This is mentioned in https://github.com/salesforce/awd-lstm-lm/issues/3. Given the work shall take place in that issue, I'll close this one.
