### ISSUE TITLE
In line 252, val_loss should be val_loss2 isn't it?

### ISSUE THREAD

**Issue by SongJeongHyun** [salesforce/awd-lstm-lm#53]
Hi, I think i just found some error of main.py.

In line 252, the val_loss should be val_loss2 right?

Because after the program switch to ASGD mode, it would not calculate val_loss so, the log of program will show no change after switching to ASGD about Validation result.

**Comment by keskarnitish** [comment]
Correct. It should be fixed now. Thanks for pointing it out. Closing the issue now, feel free to reopen if necessary.
