### ISSUE TITLE
KeyError: 'ax' in line `prm.data = optimizer.state[prm]['ax'].clone()`

### ISSUE THREAD

**Issue by wasiahmad** [salesforce/awd-lstm-lm#70]
Where the key 'ax' comes from in line: https://github.com/salesforce/awd-lstm-lm/blob/master/main.py#L245?

```
if 't0' in optimizer.param_groups[0]:
    tmp = {}
    for prm in model.parameters():
        tmp[prm] = prm.data.clone()
        prm.data = optimizer.state[prm]['ax'].clone()
```

I have made small changes to the code and after that I am getting a key error in the very next iteration whenever the code switches to the 'ASGD'. Where this key 'ax' is introduced?

**Comment by ChristineBasta** [comment]
have you found out the answer???

**Comment by shirishr** [comment]
@wasiahmad,

I also ran into the same error. Have you figured out where 'ax' is introduced? I do not want to reopen the issue if the community at large seems to have figured it out.

Thanks !!

**Comment by wohlbier** [comment]
I just hit this one too...

**Comment by shirishr** [comment]
someone from facebook team suggested a change which resolved it for me as:

```if 't0' in optimizer.param_groups[0]:
    tmp = {}
    for prm in model.parameters():
        tmp[prm] = prm.data.clone()
        if 'ax' in optimizer.state[prm]:
            prm.data = optimizer.state[prm]['ax'].clone()
```

i.e. add a check to see if ax is is in optimizer.state[prm] before cloning it.

**Comment by ChristineBasta** [comment]
@shirishr I did so too, but I am not sure this is the best approach.
I don't know when exactly optimizer.state[prm] has this ax and when not?

**Comment by shirishr** [comment]
@ChristineBasta this repo is good for upto pytorch 0.4. The issue we faced is possibly due to pytorch 0.41 or 1.0 (which is new). The original contributors' last update was 7 months ago. So my approach is use what you get and apply what you deem fit. :o)

**Comment by wohlbier** [comment]
@shirishr After using that fix I hit this issue. Did you see something similar?

```
Traceback (most recent call last):
  File "main.py", line 264, in <module>
    prm.data = tmp[prm].clone()
KeyError: Parameter containing:
tensor([[-0.1190, -0.1830,  0.4134,  0.3497],
        [-0.1435,  0.0379, -0.1902,  0.0444],
        [ 0.2124,  0.0040, -0.2450, -0.3985],
        [-0.3579,  0.2050, -0.1713,  0.0386],
        [ 0.4949, -0.1025,  0.2774, -0.2697],
        [ 0.1324, -0.1173, -0.4745, -0.1688],
        [ 0.4225, -0.0276,  0.0500,  0.1296],
        [-0.2466,  0.3820,  0.4758, -0.3580],
        [-0.2401,  0.2896, -0.1317,  0.1017],
        [ 0.2610, -0.1929,  0.0019,  0.2663],
        [-0.4190,  0.4396,  0.1641, -0.2229],
        [ 0.0550,  0.4147, -0.4291,  0.1404]], requires_grad=True)
```

**Comment by shirishr** [comment]
@wohlbier  sorry john i did not

**Comment by ChristineBasta** [comment]
@wohlbier I think at somepoint ur parameters is not trainable, did u write requires_grad=false anywhere.
I experienced this before when I was switching off the taining for some parameters.

**Comment by wohlbier** [comment]
@ChristineBasta I am not sure. It happens right after the model reports "Switching to AGSD" if that suggests anything.

**Comment by ChristineBasta** [comment]
@wohlbier I am not sure, in my case I made sure all the parameters are trainable, I add the condition of 'ax'. You did not change anything in the model?
your embeddings are still trainable?? 
you did not change the drop_out function, as it caused me a problem before?

**Comment by wohlbier** [comment]
@ChristineBasta I did not change the model. Which optimizer are you using? I was not specifying an optimizer.

I found a reference to 'ax' in the ASGD code (pytorch/torch/optim/asgd.py), but perhaps the other optimizers do not have it? I'm still looking around to see why my model fails when I apply this "fix".

**Comment by ChristineBasta** [comment]
I was using ADAM then it shifts to ASGD, and yes, other optimizers do not have it. Well, then you need to check which parameter coming up in the error and why it is not trainable. I am thinking of another fix, which maybe useful. Filter these params to include only those who are trainable. instead if prm in model. parameters, filter them to be only the trainable ones and see what happens.

**Comment by wohlbier** [comment]
I got the model to run with a filter as you suggest. I'm not sure what the effect is.

```
diff --git a/main.py b/main.py
index 8626170..37ad8ca 100644
--- a/main.py
+++ b/main.py
@@ -67,6 +67,9 @@ parser.add_argument('--when', nargs="+", type=int, default=[-1],
 args = parser.parse_args()
 args.tied = True
 
+
+args.cuda = False
+
 # Set the random seed manually for reproducibility.
 np.random.seed(args.seed)
 torch.manual_seed(args.seed)
@@ -242,7 +245,8 @@ try:
             tmp = {}
             for prm in model.parameters():
                 tmp[prm] = prm.data.clone()
-                prm.data = optimizer.state[prm]['ax'].clone()
+                if 'ax' in optimizer.state[prm]: 
+                    prm.data = optimizer.state[prm]['ax'].clone()
 
             val_loss2 = evaluate(val_data)
             print('-' * 89)
@@ -257,7 +261,10 @@ try:
                 stored_loss = val_loss2
 
             for prm in model.parameters():
-                prm.data = tmp[prm].clone()
+                try: 
+                    prm.data = tmp[prm].clone()
+                except:
+                    print("prm key not in tmp")
 
         else:
             val_loss = evaluate(val_data, eval_batch_size)
```

**Comment by li221199** [comment]
Has anyone solved @wohlbier  problem?I have the same problem ,My pytorch is vesion1.0.1

**Comment by ahmetumutdurmus** [comment]
So I might have somewhat of an answer if anyone is still interested?

**Comment by boknilev** [comment]
Yes, @ahmetumutdurmus , would love an answer and fix.

**Comment by MHashemzadeh** [comment]
> Yes, @ahmetumutdurmus , would love an answer and fix.



> So I might have somewhat of an answer if anyone is still interested?

Yes please! I still have this problem

**Comment by Sahar-Abdelnabi** [comment]
> @shirishr After using that fix I hit this issue. Did you see something similar?
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 264, in <module>
>     prm.data = tmp[prm].clone()
> KeyError: Parameter containing:
> tensor([[-0.1190, -0.1830,  0.4134,  0.3497],
>         [-0.1435,  0.0379, -0.1902,  0.0444],
>         [ 0.2124,  0.0040, -0.2450, -0.3985],
>         [-0.3579,  0.2050, -0.1713,  0.0386],
>         [ 0.4949, -0.1025,  0.2774, -0.2697],
>         [ 0.1324, -0.1173, -0.4745, -0.1688],
>         [ 0.4225, -0.0276,  0.0500,  0.1296],
>         [-0.2466,  0.3820,  0.4758, -0.3580],
>         [-0.2401,  0.2896, -0.1317,  0.1017],
>         [ 0.2610, -0.1929,  0.0019,  0.2663],
>         [-0.4190,  0.4396,  0.1641, -0.2229],
>         [ 0.0550,  0.4147, -0.4291,  0.1404]], requires_grad=True)
> ```

Has anyone found a solution to that?
I am also facing the same error. I didn't change the model or optimizer, I am using the default values

**Comment by mourga** [comment]
@shirishr @Sahar-Abdelnabi @MHashemzadeh @boknilev I had the same issue and I found a workaround if you are interested. I use PyTorch 1.2.0.

First, I changed [lines 241-245 in main.py](https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/main.py#L241) into:
```
        if 't0' in optimizer.param_groups[0]: # if ASGD
            tmp = {}
            for prm in model.parameters():
                tmp[prm] = prm.data.clone()
                if 'ax' in optimizer.state[prm]: # added this line because of error: File "main.py", line 268, in <module> prm.data = optimizer.state[prm]['ax'].clone() KeyError: 'ax'
                    prm.data = optimizer.state[prm]['ax'].clone()
```
Still, I had the same `KeyError: Parameter containing: ...` in lines [259-260](https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/main.py#L259) like you, so after debugging line by line I noticed that after [evaluate in line 247](https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/main.py#L247) three new parameters where added at `model.parameters()` that are not in the `tmp` dictionary (I still don't know why). Anyway, this is the cause of `KeyError` (attempting to access `tpm[prm]` when the key `prm` is not in the dictionary `tmp`).

My solution is this (replace lines [259-260](https://github.com/salesforce/awd-lstm-lm/blob/32fcb42562aeb5c7e6c9dec3f2a3baaaf68a5cb5/main.py#L259) with the following):
```
            nparams = 0
            nparams_in_temp_keys = 0
            for prm in model.parameters():
                nparams += 1
                if prm in tmp.keys():
                    nparams_in_temp_keys += 1
                    prm.data = tmp[prm].clone()
            print('params {}, params in tmp keys: {}'.format(nparams,nparams_in_temp_keys))
```
The `nparams, nparams_in_temp_keys, print` are all for debugging purposes you can simply remove them.

With these changes the code works fine. I have open-sourced the codebase with the changes [here](https://github.com/mourga/awd-lstm-lm) with instructions on how to make the correct conda environment with PyTorch 1.2.0.
